version: '2'
services:
  master:
    image: redis:3.2.12
    restart: always
    container_name: redis-master
    command: redis-server /usr/local/etc/redis/redis-master.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis-master.conf

  slave1:
    image: redis:3.2.12
    restart: always
    container_name: redis-slave-1
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  slave2:
    image: redis:3.2.12
    restart: always
    container_name: redis-slave-2
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6381:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
