version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    volumes:
      - "nfs-vol:/usr/share/nginx/html"

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  nfs-vol:
    driver_opts:
      type: "nfs"
      o: "addr=172.16.81.1,nolock,soft,rw"
      device: ":/ext/test"