version: '3.4'
services:
  serverA:
    # build: .
    image: fig/srs3:latest
    # restart: always
    container_name: serverA
    network_mode: "host"
    # ports:
    # - "19350:1935"
    # - "19850:1985"
    # - "8080:8080"
    volumes:
    - ./logrotate.d/logrotate-srs:/etc/logrotate.d/logrotate-srs
    - ./config/origin.cluster.serverA.conf:/usr/local/srs/conf/srs.conf
    # networks:
    # - fig-srs3

  edgeA:
    # build: .
    image: fig/srs3:latest
    # restart: always
    container_name: edgeA
    network_mode: "host"
    # ports:
    # - "19352:1935"
    # - "19852:1985"
    # - "8082:8080"
    volumes:
    - ./logrotate.d/logrotate-srs:/etc/logrotate.d/logrotate-srs
    - ./config/origin.cluster.edgeA.conf:/usr/local/srs/conf/srs.conf
    - ./hls_share:/usr/local/srs/objs/nginx/html
    # networks:
    # - fig-srs3

  nginx:
    # build: .
    image: nginx
    # restart: always
    container_name: nginx
    network_mode: "host"
    # ports:
    # - "19352:1935"
    # - "19852:1985"
    # - "8082:8080"
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./hls_share:/etc/nginx/html
    # networks:
    # - fig-srs3

# networks:
#   fig-srs3: